import type { Contact, Activity } from "./types";

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "1",
    name: "Alice Johnson",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=60",
    title: "Director of Giving",
    company: "TechFoundations",
    email: "alice@techfoundations.org",
    phone: "+1 555-0101",
    value: 50000,
    stage: "Proposal",
    owner: "Me",
    lastActivity: "2 hours ago",
    tags: ["High Value"],
    city: "San Francisco",
    bio: "Alice leads philanthropy for TechFoundations. She's interested in sustainable water projects.",
    activities: [
      {
        id: "a1",
        type: "meeting",
        date: "2024-12-18T10:00:00Z",
        title: "Q4 Strategy Session",
        description: "Discussed scaling the well project in Chiang Mai.",
      },
      {
        id: "a2",
        type: "gift",
        date: "2024-11-15T09:00:00Z",
        title: "Corporate Grant",
        amount: 25000,
      },
    ],
  },
  {
    id: "2",
    name: "Bob Smith",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=60",
    title: "CEO",
    company: "Global Ventures",
    email: "bob@globalventures.com",
    phone: "+1 555-0102",
    value: 12000,
    stage: "Meeting",
    owner: "Sarah",
    lastActivity: "1 day ago",
    tags: ["Corporate"],
    city: "New York",
    bio: "Long-time supporter of educational initiatives in South America.",
    activities: [],
  },
  {
    id: "3",
    name: "Clara Wilson",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=60",
    title: "Foundation Manager",
    company: "Wilson Family Trust",
    email: "clara@wilsontrust.org",
    phone: "+1 555-0103",
    value: 75000,
    stage: "Won",
    owner: "Me",
    lastActivity: "3 days ago",
    tags: ["Major Donor", "High Value"],
    city: "Chicago",
    bio: "Clara manages a family foundation focused on education and clean water initiatives.",
    activities: [
      {
        id: "c1",
        type: "gift",
        date: "2024-12-10T09:00:00Z",
        title: "Annual Grant",
        amount: 75000,
      },
    ],
  },
  {
    id: "4",
    name: "David Chen",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=60",
    title: "Senior Partner",
    company: "Chen & Associates",
    email: "david@chenassociates.com",
    phone: "+1 555-0104",
    value: 8500,
    stage: "Contacted",
    owner: "Sarah",
    lastActivity: "5 days ago",
    tags: ["New Lead"],
    city: "Los Angeles",
    bio: "David is exploring philanthropic opportunities in Southeast Asia.",
    activities: [
      {
        id: "d1",
        type: "email",
        date: "2024-12-05T14:00:00Z",
        title: "Initial Outreach",
        description: "Sent intro email about our mission.",
      },
    ],
  },
  {
    id: "5",
    name: "Emily Ross",
    avatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=60",
    title: "VP of Philanthropy",
    company: "Ross Enterprises",
    email: "emily@ross-ent.com",
    phone: "+1 555-0105",
    value: 25000,
    stage: "New",
    owner: "Me",
    lastActivity: "1 week ago",
    tags: ["New Lead"],
    city: "Boston",
    bio: "Emily is looking for new projects to support in 2025.",
    activities: [],
  },
  {
    id: "6",
    name: "Frank Miller",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=60",
    title: "Board Member",
    company: "Miller Foundation",
    email: "frank@millerfoundation.org",
    phone: "+1 555-0106",
    value: 100000,
    stage: "Proposal",
    owner: "Sarah",
    lastActivity: "2 days ago",
    tags: ["High Value", "Major Donor"],
    city: "Miami",
    bio: "Frank has been a long-time supporter and is considering a major gift.",
    activities: [
      {
        id: "f1",
        type: "meeting",
        date: "2024-12-15T11:00:00Z",
        title: "Gift Proposal Meeting",
        description: "Presented multi-year giving plan.",
      },
    ],
  },
];
