"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import _donor_dashboard_main from "./donor-dashboard-main.bones.json";

configureBoneyard({ color: "rgba(0,0,0,0.06)", animate: "pulse" });

registerBones({
  "donor-dashboard-main": _donor_dashboard_main,
});
