"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import _missionary_tasks_list from "./missionary-tasks-list.bones.json";

configureBoneyard({ color: "rgba(0,0,0,0.06)", animate: "pulse" });

registerBones({
  "missionary-tasks-list": _missionary_tasks_list,
});
