/**
 * Current ISO-4217 monetary units, SIX List One, published 2026-09-17.
 * https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml
 * N.A. units (metals, testing and no-currency codes) have no monetary exponent
 * and are deliberately excluded. CLF/UYW fund units retain their ISO exponent4.
 * Stripe representation constraints: https://docs.stripe.com/currencies
 * Metadata represents money; it never qualifies a currency for a payment route.
 * Mirror changes into the SQL currency_metadata seed in a forward migration.
 */
export type CurrencyMetadata = Readonly<{
  code: string;
  exponent: 0 | 2 | 3 | 4;
  stripeChargeExponent: number;
  stripePayoutExponent: number;
  stripeChargeMultiple: number;
  stripePayoutMultiple: number;
}>;

export const CURRENCY_METADATA: Readonly<Record<string, CurrencyMetadata>> =
  Object.freeze({
    AED: Object.freeze({
      code: "AED",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    AFN: Object.freeze({
      code: "AFN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ALL: Object.freeze({
      code: "ALL",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    AMD: Object.freeze({
      code: "AMD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    AOA: Object.freeze({
      code: "AOA",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ARS: Object.freeze({
      code: "ARS",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    AUD: Object.freeze({
      code: "AUD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    AWG: Object.freeze({
      code: "AWG",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    AZN: Object.freeze({
      code: "AZN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BAM: Object.freeze({
      code: "BAM",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BBD: Object.freeze({
      code: "BBD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BDT: Object.freeze({
      code: "BDT",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BHD: Object.freeze({
      code: "BHD",
      exponent: 3,
      stripeChargeExponent: 3,
      stripePayoutExponent: 3,
      stripeChargeMultiple: 10,
      stripePayoutMultiple: 10,
    }),
    BIF: Object.freeze({
      code: "BIF",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BMD: Object.freeze({
      code: "BMD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BND: Object.freeze({
      code: "BND",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BOB: Object.freeze({
      code: "BOB",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BOV: Object.freeze({
      code: "BOV",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BRL: Object.freeze({
      code: "BRL",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BSD: Object.freeze({
      code: "BSD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BTN: Object.freeze({
      code: "BTN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BWP: Object.freeze({
      code: "BWP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BYN: Object.freeze({
      code: "BYN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    BZD: Object.freeze({
      code: "BZD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CAD: Object.freeze({
      code: "CAD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CDF: Object.freeze({
      code: "CDF",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CHE: Object.freeze({
      code: "CHE",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CHF: Object.freeze({
      code: "CHF",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CHW: Object.freeze({
      code: "CHW",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CLF: Object.freeze({
      code: "CLF",
      exponent: 4,
      stripeChargeExponent: 4,
      stripePayoutExponent: 4,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CLP: Object.freeze({
      code: "CLP",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CNY: Object.freeze({
      code: "CNY",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    COP: Object.freeze({
      code: "COP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    COU: Object.freeze({
      code: "COU",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CRC: Object.freeze({
      code: "CRC",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CUP: Object.freeze({
      code: "CUP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CVE: Object.freeze({
      code: "CVE",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    CZK: Object.freeze({
      code: "CZK",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    DJF: Object.freeze({
      code: "DJF",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    DKK: Object.freeze({
      code: "DKK",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    DOP: Object.freeze({
      code: "DOP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    DZD: Object.freeze({
      code: "DZD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    EGP: Object.freeze({
      code: "EGP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ERN: Object.freeze({
      code: "ERN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ETB: Object.freeze({
      code: "ETB",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    EUR: Object.freeze({
      code: "EUR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    FJD: Object.freeze({
      code: "FJD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    FKP: Object.freeze({
      code: "FKP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    GBP: Object.freeze({
      code: "GBP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    GEL: Object.freeze({
      code: "GEL",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    GHS: Object.freeze({
      code: "GHS",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    GIP: Object.freeze({
      code: "GIP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    GMD: Object.freeze({
      code: "GMD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    GNF: Object.freeze({
      code: "GNF",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    GTQ: Object.freeze({
      code: "GTQ",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    GYD: Object.freeze({
      code: "GYD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    HKD: Object.freeze({
      code: "HKD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    HNL: Object.freeze({
      code: "HNL",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    HTG: Object.freeze({
      code: "HTG",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    HUF: Object.freeze({
      code: "HUF",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 100,
    }),
    IDR: Object.freeze({
      code: "IDR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ILS: Object.freeze({
      code: "ILS",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    INR: Object.freeze({
      code: "INR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    IQD: Object.freeze({
      code: "IQD",
      exponent: 3,
      stripeChargeExponent: 3,
      stripePayoutExponent: 3,
      stripeChargeMultiple: 10,
      stripePayoutMultiple: 10,
    }),
    IRR: Object.freeze({
      code: "IRR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ISK: Object.freeze({
      code: "ISK",
      exponent: 0,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 100,
      stripePayoutMultiple: 100,
    }),
    JMD: Object.freeze({
      code: "JMD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    JOD: Object.freeze({
      code: "JOD",
      exponent: 3,
      stripeChargeExponent: 3,
      stripePayoutExponent: 3,
      stripeChargeMultiple: 10,
      stripePayoutMultiple: 10,
    }),
    JPY: Object.freeze({
      code: "JPY",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    KES: Object.freeze({
      code: "KES",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    KGS: Object.freeze({
      code: "KGS",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    KHR: Object.freeze({
      code: "KHR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    KMF: Object.freeze({
      code: "KMF",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    KPW: Object.freeze({
      code: "KPW",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    KRW: Object.freeze({
      code: "KRW",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    KWD: Object.freeze({
      code: "KWD",
      exponent: 3,
      stripeChargeExponent: 3,
      stripePayoutExponent: 3,
      stripeChargeMultiple: 10,
      stripePayoutMultiple: 10,
    }),
    KYD: Object.freeze({
      code: "KYD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    KZT: Object.freeze({
      code: "KZT",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    LAK: Object.freeze({
      code: "LAK",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    LBP: Object.freeze({
      code: "LBP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    LKR: Object.freeze({
      code: "LKR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    LRD: Object.freeze({
      code: "LRD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    LSL: Object.freeze({
      code: "LSL",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    LYD: Object.freeze({
      code: "LYD",
      exponent: 3,
      stripeChargeExponent: 3,
      stripePayoutExponent: 3,
      stripeChargeMultiple: 10,
      stripePayoutMultiple: 10,
    }),
    MAD: Object.freeze({
      code: "MAD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MDL: Object.freeze({
      code: "MDL",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MGA: Object.freeze({
      code: "MGA",
      exponent: 2,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MKD: Object.freeze({
      code: "MKD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MMK: Object.freeze({
      code: "MMK",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MNT: Object.freeze({
      code: "MNT",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MOP: Object.freeze({
      code: "MOP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MRU: Object.freeze({
      code: "MRU",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MUR: Object.freeze({
      code: "MUR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MVR: Object.freeze({
      code: "MVR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MWK: Object.freeze({
      code: "MWK",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MXN: Object.freeze({
      code: "MXN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MXV: Object.freeze({
      code: "MXV",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MYR: Object.freeze({
      code: "MYR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    MZN: Object.freeze({
      code: "MZN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    NAD: Object.freeze({
      code: "NAD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    NGN: Object.freeze({
      code: "NGN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    NIO: Object.freeze({
      code: "NIO",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    NOK: Object.freeze({
      code: "NOK",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    NPR: Object.freeze({
      code: "NPR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    NZD: Object.freeze({
      code: "NZD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    OMR: Object.freeze({
      code: "OMR",
      exponent: 3,
      stripeChargeExponent: 3,
      stripePayoutExponent: 3,
      stripeChargeMultiple: 10,
      stripePayoutMultiple: 10,
    }),
    PAB: Object.freeze({
      code: "PAB",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    PEN: Object.freeze({
      code: "PEN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    PGK: Object.freeze({
      code: "PGK",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    PHP: Object.freeze({
      code: "PHP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    PKR: Object.freeze({
      code: "PKR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    PLN: Object.freeze({
      code: "PLN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    PYG: Object.freeze({
      code: "PYG",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    QAR: Object.freeze({
      code: "QAR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    RON: Object.freeze({
      code: "RON",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    RSD: Object.freeze({
      code: "RSD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    RUB: Object.freeze({
      code: "RUB",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    RWF: Object.freeze({
      code: "RWF",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SAR: Object.freeze({
      code: "SAR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SBD: Object.freeze({
      code: "SBD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SCR: Object.freeze({
      code: "SCR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SDG: Object.freeze({
      code: "SDG",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SEK: Object.freeze({
      code: "SEK",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SGD: Object.freeze({
      code: "SGD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SHP: Object.freeze({
      code: "SHP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SLE: Object.freeze({
      code: "SLE",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SOS: Object.freeze({
      code: "SOS",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SRD: Object.freeze({
      code: "SRD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SSP: Object.freeze({
      code: "SSP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    STN: Object.freeze({
      code: "STN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SVC: Object.freeze({
      code: "SVC",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SYP: Object.freeze({
      code: "SYP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    SZL: Object.freeze({
      code: "SZL",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    THB: Object.freeze({
      code: "THB",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    TJS: Object.freeze({
      code: "TJS",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    TMT: Object.freeze({
      code: "TMT",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    TND: Object.freeze({
      code: "TND",
      exponent: 3,
      stripeChargeExponent: 3,
      stripePayoutExponent: 3,
      stripeChargeMultiple: 10,
      stripePayoutMultiple: 10,
    }),
    TOP: Object.freeze({
      code: "TOP",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    TRY: Object.freeze({
      code: "TRY",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    TTD: Object.freeze({
      code: "TTD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    TWD: Object.freeze({
      code: "TWD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 100,
    }),
    TZS: Object.freeze({
      code: "TZS",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    UAH: Object.freeze({
      code: "UAH",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    UGX: Object.freeze({
      code: "UGX",
      exponent: 0,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 100,
      stripePayoutMultiple: 100,
    }),
    USD: Object.freeze({
      code: "USD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    USN: Object.freeze({
      code: "USN",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    UYI: Object.freeze({
      code: "UYI",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    UYU: Object.freeze({
      code: "UYU",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    UYW: Object.freeze({
      code: "UYW",
      exponent: 4,
      stripeChargeExponent: 4,
      stripePayoutExponent: 4,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    UZS: Object.freeze({
      code: "UZS",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    VED: Object.freeze({
      code: "VED",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    VES: Object.freeze({
      code: "VES",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    VND: Object.freeze({
      code: "VND",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    VUV: Object.freeze({
      code: "VUV",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    WST: Object.freeze({
      code: "WST",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    XAD: Object.freeze({
      code: "XAD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    XAF: Object.freeze({
      code: "XAF",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    XCD: Object.freeze({
      code: "XCD",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    XCG: Object.freeze({
      code: "XCG",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    XOF: Object.freeze({
      code: "XOF",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    XPF: Object.freeze({
      code: "XPF",
      exponent: 0,
      stripeChargeExponent: 0,
      stripePayoutExponent: 0,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    YER: Object.freeze({
      code: "YER",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ZAR: Object.freeze({
      code: "ZAR",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ZMW: Object.freeze({
      code: "ZMW",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
    ZWG: Object.freeze({
      code: "ZWG",
      exponent: 2,
      stripeChargeExponent: 2,
      stripePayoutExponent: 2,
      stripeChargeMultiple: 1,
      stripePayoutMultiple: 1,
    }),
  });
