export const LOCAL_SUPABASE_URL = "http://127.0.0.1:54321";
export const LOCAL_DATABASE_URL =
  "postgresql://postgres:postgres@127.0.0.1:54322/postgres";
export const LOCAL_ADMIN_URL = "http://127.0.0.1:3030";
export const LOCAL_DONOR_URL = "http://127.0.0.1:3000";
export const LOCAL_PLAYWRIGHT_DONOR_URL = "http://127.0.0.1:3005";
export const LOCAL_PLAYWRIGHT_ADMIN_URL = "http://127.0.0.1:3030";
export const LOCAL_PAYLOAD_SECRET = "payload-local-dev-secret";

export const DEMO_PUBLIC_TENANT_ID = "00000000-0000-0000-0000-000000000001";
export const DEMO_PUBLIC_TENANT_SLUG = "give-hope-demo";
export const DEMO_PUBLIC_TENANT_NAME = "GiveHope Demo Organization";
export const DEMO_ADMIN_USER_ID = "11111111-1111-1111-1111-111111111111";
export const DEMO_ADMIN_EMAIL = "demo-owner@givehope.test";
export const DEMO_ADMIN_PASSWORD = "demo-password";

export const SECOND_PUBLIC_TENANT_ID = "00000000-0000-0000-0000-000000000002";
export const SECOND_PUBLIC_TENANT_SLUG = "second-demo";
export const SECOND_PUBLIC_TENANT_NAME = "Second Local Demo Organization";

export const LOCAL_SEED_SLUGS = {
  draftPage: "local-cms-draft-preview",
  homePage: "local-cms-home",
  ministryUpdate: "local-ministry-update",
  projectPage: "local-project",
  secondTenantPage: "local-cms-home",
};

export const LOCAL_TEMPLATE_KEYS = {
  ministryUpdate: "ministry-update-local",
  missionaryGiving: "missionary-giving-local",
  project: "project-local",
  standard: "standard-local",
};

export const EDITORIAL_COLLECTIONS = [
  "pages",
  "navigation",
  "missionary-profiles",
  "ministry-updates",
  "media",
  "page-templates",
  "missionary-giving-pages",
  "project-pages",
];

export const LOCAL_ENV_DEFAULTS = {
  NODE_ENV: "development",
  NEXT_PUBLIC_SUPABASE_URL: LOCAL_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "",
  SUPABASE_DB_URL: LOCAL_DATABASE_URL,
  PAYLOAD_DATABASE_URI: LOCAL_DATABASE_URL,
  PAYLOAD_DISABLE_SCHEMA_PUSH: "1",
  PAYLOAD_SECRET: LOCAL_PAYLOAD_SECRET,
  CMS_BASE_URL: LOCAL_ADMIN_URL,
  NEXT_PUBLIC_DONOR_URL: LOCAL_DONOR_URL,
  DONOR_APP_URL: LOCAL_DONOR_URL,
  ALLOW_DEMO_ACCOUNTS: "true",
  DEMO_ONLY_LOGIN: "false",
  DEMO_ADMIN_EMAIL,
  DEMO_PASSWORD: DEMO_ADMIN_PASSWORD,
  E2E_AUTH_BYPASS: "false",
  PLAYWRIGHT_BASE_URL: LOCAL_PLAYWRIGHT_DONOR_URL,
  PLAYWRIGHT_ADMIN_BASE_URL: LOCAL_PLAYWRIGHT_ADMIN_URL,
  CMS_WEB_STUDIO_NATIVE_PAGES: "true",
  CMS_WEB_STUDIO_NATIVE_NAVIGATION: "true",
  CMS_WEB_STUDIO_NATIVE_MISSIONARY_PROFILES: "true",
  CMS_WEB_STUDIO_NATIVE_MINISTRY_UPDATES: "true",
  CMS_WEB_STUDIO_NATIVE_MEDIA: "true",
  CMS_WEB_STUDIO_NATIVE_PAGE_TEMPLATES: "true",
  CMS_WEB_STUDIO_NATIVE_MISSIONARY_GIVING_PAGES: "true",
  CMS_WEB_STUDIO_NATIVE_PROJECT_PAGES: "true",
  CMS_LOCAL_DEFAULT_TENANT_SLUG: DEMO_PUBLIC_TENANT_SLUG,
};

export const REQUIRED_LOCAL_ENV_KEYS = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "SUPABASE_DB_URL",
  "PAYLOAD_DATABASE_URI",
  "PAYLOAD_DISABLE_SCHEMA_PUSH",
  "PAYLOAD_SECRET",
  "CMS_BASE_URL",
  "NEXT_PUBLIC_DONOR_URL",
  "DONOR_APP_URL",
  "ALLOW_DEMO_ACCOUNTS",
  "DEMO_ADMIN_EMAIL",
  "DEMO_PASSWORD",
  "E2E_AUTH_BYPASS",
  "CMS_LOCAL_DEFAULT_TENANT_SLUG",
];

export function createLexicalRichText(text) {
  return {
    root: {
      type: "root",
      children: [
        {
          type: "paragraph",
          children: [
            {
              type: "text",
              detail: 0,
              format: 0,
              mode: "normal",
              style: "",
              text,
              version: 1,
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          textFormat: 0,
          textStyle: "",
          version: 1,
        },
      ],
      direction: null,
      format: "",
      indent: 0,
      version: 1,
    },
  };
}

export function createLocalPageLayout({ headline, mediaId, variant }) {
  const prefix = variant === "project" ? "Project" : "Local CMS";

  return [
    {
      blockType: "hero",
      eyebrow: "Local Web Studio",
      headline,
      subheading:
        "Seeded content that proves Payload CMS, public endpoints, preview, and donor rendering work without hosted services.",
      backgroundImage: mediaId,
      primaryCtaLabel: "Give locally",
      primaryCtaHref:
        variant === "project" ? "/projects/local-project" : "/give",
    },
    {
      blockType: "rich-text",
      heading: `${prefix} overview`,
      body: createLexicalRichText(
        "This section is generated by the local CMS seed and is safe to edit, preview, publish, reset, and recreate.",
      ),
    },
    {
      blockType: "call-to-action",
      headline: "Continue the local CMS proof",
      copy: "This CTA is sanitized by the public CMS serializer and resolves through local routes.",
      buttonLabel: "Open Web Studio",
      buttonHref: "/web-studio",
      openInNewTab: false,
    },
    {
      blockType: "impact-stats",
      heading: "Local proof points",
      items: [
        {
          label: "Seeded templates",
          value: "4",
          description: "Standard, giving, project, and ministry update.",
        },
        {
          label: "Local tenant",
          value: "1",
          description: "Loopback host resolution maps to give-hope-demo.",
        },
      ],
    },
  ];
}
