"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import _admin_contributions_content from "./admin-contributions-content.bones.json";

configureBoneyard({ color: "rgba(0,0,0,0.06)", animate: "pulse" });

registerBones({
  "admin-contributions-content": _admin_contributions_content,
});
