import { z } from "zod";

export const donationStatusSchema = z.enum([
  "pending",
  "processing",
  "completed",
  "failed",
  "refunded",
]);

export const donorActivitySchema = z.object({
  id: z.string().min(1),
  donor_id: z.string().nullable(),
  type: z.string().min(1),
  title: z.string().min(1),
  description: z.string().nullable(),
  date: z.string().nullable(),
  amount: z.number().nullable(),
  status: z.string().nullable(),
  gift_type: z.string().nullable(),
  note: z.string().nullable(),
  created_at: z.string().min(1),
  updated_at: z.string().min(1),
});

export const donorPledgeSchema = z.object({
  id: z.string().min(1),
  tenant_id: z.string().nullable(),
  donor_id: z.string().nullable(),
  missionary_id: z.string().nullable(),
  fund_id: z.string().nullable(),
  amount: z.number(),
  currency: z.string(),
  frequency: z.string().nullable(),
  status: z.string(),
  start_date: z.string().nullable(),
  end_date: z.string().nullable(),
  next_payment_date: z.string().nullable(),
  stripe_subscription_id: z.string().nullable(),
  billing_day_of_month: z.number().int().nullable(),
  billing_timezone: z.string().nullable(),
  stripe_payment_method_id: z.string().nullable(),
  retry_count: z.number().int(),
  last_charge_at: z.string().nullable(),
  last_charge_attempt: z.string().nullable(),
  failed_charge_count: z.number().int(),
  pause_reason: z.string().nullable(),
  paused_at: z.string().nullable(),
  next_charge_at: z.string().nullable(),
  total_paid: z.number(),
  total_expected: z.number(),
  payments_completed: z.number().int().nullable(),
  payments_remaining: z.number().int().nullable(),
  payment_method: z.string().nullable(),
  created_at: z.string().min(1),
  updated_at: z.string().min(1),
});

export const donationSchema = z.object({
  id: z.string().min(1),
  tenant_id: z.string().nullable(),
  donor_id: z.string().nullable(),
  missionary_id: z.string().nullable(),
  fund_id: z.string().nullable(),
  amount: z.number(),
  currency: z.string(),
  status: donationStatusSchema,
  donation_type: z.string().nullable(),
  payment_method: z.string().nullable(),
  is_recurring: z.boolean().nullable(),
  recurring_interval: z.string().nullable(),
  notes: z.string().nullable(),
  stripe_payment_intent_id: z.string().nullable(),
  gift_date: z.string().min(1),
  campaign_id: z.string().nullable(),
  pledge_id: z.string().nullable(),
  processed_at: z.string().nullable(),
  completed_at: z.string().nullable(),
  failed_at: z.string().nullable(),
  error_code: z.string().nullable(),
  error_message: z.string().nullable(),
  stripe_charge_id: z.string().nullable(),
  refunded_at: z.string().nullable(),
  refund_amount: z.number(),
  source: z.string().nullable(),
  created_at: z.string().min(1),
  updated_at: z.string().min(1),
});

export const fundSchema = z.object({
  id: z.string().min(1),
  tenant_id: z.string().min(1),
  name: z.string(),
  description: z.string().nullable(),
  target_amount: z.number(),
  goal_amount: z.number(),
  current_amount: z.number(),
  currency: z.string().nullable(),
  missionary_id: z.string().nullable(),
  is_active: z.boolean(),
  start_date: z.string().nullable(),
  end_date: z.string().nullable(),
  created_at: z.string().min(1),
  updated_at: z.string().min(1),
});
