import { z } from "zod";

export const userRoleSchema = z.enum([
  "donor",
  "missionary",
  "admin",
  "staff",
  "super_admin",
]);

export const profileSchema = z.object({
  id: z.string().min(1),
  tenant_id: z.string().min(1),
  user_id: z.string().min(1),
  role: userRoleSchema,
  first_name: z.string(),
  last_name: z.string(),
  display_name: z.string().nullable(),
  email: z.string(),
  avatar_url: z.string().nullable(),
  phone: z.string().nullable(),
  created_at: z.string().min(1),
  updated_at: z.string().min(1),
});

export const missionarySchema = z.object({
  id: z.string().min(1),
  tenant_id: z.string().min(1),
  profile_id: z.string().min(1),
  bio: z.string().nullable(),
  mission_field: z.string().nullable(),
  funding_goal: z.number(),
  current_funding: z.number(),
  phone: z.string().nullable(),
  location: z.string().nullable(),
  tagline: z.string().nullable(),
  social_links: z.record(z.string(), z.unknown()),
  created_at: z.string().min(1),
  updated_at: z.string().min(1),
});

export const donorSchema = z.object({
  id: z.string().min(1),
  tenant_id: z.string().min(1),
  profile_id: z.string().nullable(),
  missionary_id: z.string().nullable(),
  name: z.string().nullable(),
  email: z.string().nullable(),
  phone: z.string().nullable(),
  mobile: z.string().nullable(),
  work_phone: z.string().nullable(),
  preferred_contact: z.string().nullable(),
  avatar_url: z.string().nullable(),
  location: z.string().nullable(),
  type: z.string().nullable(),
  status: z.string().nullable(),
  giving_preferences: z.record(z.string(), z.unknown()),
  total_given: z.number(),
  first_gift_date: z.string().nullable(),
  last_gift_date: z.string().nullable(),
  last_gift_amount: z.number().nullable(),
  gift_count: z.number().int(),
  frequency: z.string().nullable(),
  joined_date: z.string().nullable(),
  tags: z.array(z.string()).nullable(),
  score: z.number().nullable(),
  address: z.record(z.string(), z.unknown()).nullable(),
  work_address: z.record(z.string(), z.unknown()).nullable(),
  website: z.string().nullable(),
  organization: z.string().nullable(),
  title: z.string().nullable(),
  birthday: z.string().nullable(),
  anniversary: z.string().nullable(),
  spouse: z.string().nullable(),
  notes: z.string().nullable(),
  do_not_contact: z.boolean(),
  do_not_email: z.boolean(),
  receipt_email_frequency: z.string(),
  default_update_frequency: z.string().nullable(),
  preferred_language: z.string(),
  has_active_pledge: z.boolean().nullable(),
  stripe_customer_id: z.string().nullable(),
  created_at: z.string().min(1),
  updated_at: z.string().min(1),
});
