import {
  Accessibility,
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  AtSign,
  BadgePercent,
  BarChart,
  BarChart3,
  Bed,
  BedDouble,
  Bell,
  BellOff,
  BellRing,
  Bold,
  Bookmark,
  BookmarkCheck,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  ChartNoAxesCombined,
  ChartPie,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CirclePercent,
  CirclePlus,
  CircleUser,
  Clipboard,
  ClipboardList,
  Clock,
  CloudSun,
  Code,
  Coffee,
  Columns,
  Command,
  Compass,
  Copy,
  CornerDownRight,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  DoorOpen,
  Download,
  DownloadCloud,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FileCheck,
  FileCode,
  FileDown,
  FileHeart,
  FileInput,
  FilePlus,
  FileQuestion,
  FileSearch,
  FileSignature,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  FolderSearch,
  Gift,
  Github,
  Globe,
  GraduationCap,
  Grid,
  GripVertical,
  HandHeart,
  Heading1,
  Heading2,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  History,
  Home,
  Image,
  ImageOff,
  ImagePlus,
  Inbox,
  Info,
  Instagram,
  Italic,
  Key,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Library,
  LifeBuoy,
  Link,
  Link2,
  Link2Off,
  Linkedin,
  List,
  ListFilter,
  ListOrdered,
  ListTodo,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic2,
  Minimize2,
  Minus,
  Monitor,
  MonitorSmartphone,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointerClick,
  Navigation,
  Newspaper,
  OctagonX,
  Palette,
  PanelLeft,
  Paperclip,
  PauseCircle,
  PenSquare,
  PenTool,
  Pencil,
  Phone,
  PieChart,
  Pin,
  PinOff,
  Plane,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Presentation,
  Printer,
  QrCode,
  Quote,
  Radio,
  Receipt,
  Redo,
  Redo2,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Rss,
  Save,
  ScanLine,
  Search,
  Send,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquarePen,
  SquarePlus,
  Star,
  Strikethrough,
  Sun,
  Tag,
  Target,
  Terminal,
  Ticket,
  Timer,
  ToggleLeft,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Twitter,
  Underline,
  Undo,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  UserX,
  Users,
  Utensils,
  Wallet,
  Wand2,
  Webhook,
  Wifi,
  X,
  XCircle,
  Youtube,
  Zap,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react'

// Main registry - simple re-exports
export {
  Accessibility,
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  AtSign,
  BadgePercent,
  BarChart,
  BarChart3,
  Bed,
  BedDouble,
  Bell,
  BellOff,
  BellRing,
  Bold,
  Bookmark,
  BookmarkCheck,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  ChartNoAxesCombined,
  ChartPie,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CirclePercent,
  CirclePlus,
  CircleUser,
  Clipboard,
  ClipboardList,
  Clock,
  CloudSun,
  Code,
  Coffee,
  Columns,
  Command,
  Compass,
  Copy,
  CornerDownRight,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  DoorOpen,
  Download,
  DownloadCloud,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FileCheck,
  FileCode,
  FileDown,
  FileHeart,
  FileInput,
  FilePlus,
  FileQuestion,
  FileSearch,
  FileSignature,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  FolderSearch,
  Gift,
  Github,
  Globe,
  GraduationCap,
  Grid,
  GripVertical,
  HandHeart,
  Heading1,
  Heading2,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  History,
  Home,
  Image,
  ImageOff,
  ImagePlus,
  Inbox,
  Info,
  Instagram,
  Italic,
  Key,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Library,
  LifeBuoy,
  Link,
  Link2,
  Link2Off,
  Linkedin,
  List,
  ListFilter,
  ListOrdered,
  ListTodo,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic2,
  Minimize2,
  Minus,
  Monitor,
  MonitorSmartphone,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointerClick,
  Navigation,
  Newspaper,
  OctagonX,
  Palette,
  PanelLeft,
  Paperclip,
  PauseCircle,
  PenSquare,
  PenTool,
  Pencil,
  Phone,
  PieChart,
  Pin,
  PinOff,
  Plane,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Presentation,
  Printer,
  QrCode,
  Quote,
  Radio,
  Receipt,
  Redo,
  Redo2,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Rss,
  Save,
  ScanLine,
  Search,
  Send,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquarePen,
  SquarePlus,
  Star,
  Strikethrough,
  Sun,
  Tag,
  Target,
  Terminal,
  Ticket,
  Timer,
  ToggleLeft,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Twitter,
  Underline,
  Undo,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  UserX,
  Users,
  Utensils,
  Wallet,
  Wand2,
  Webhook,
  Wifi,
  X,
  XCircle,
  Youtube,
  Zap,
  type LucideIcon,
  type LucideProps,
}

// Unified Aliases (modernizing common aliases)
// Use specific names for clarity in the UI components
export {
  X as XIcon,
  Search as SearchIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Circle as CircleIcon,
  Plus as PlusIcon,
  Minus as MinusIcon,
  PanelLeft as PanelLeftIcon, // Fixes sidebar.tsx dependency
  MoreHorizontal as MoreHorizontalIcon,
  MoreVertical as MoreVerticalIcon,
  CircleCheck as CircleCheckIcon,
  CirclePlus as CirclePlusIcon,
  CircleUser as CircleUserIcon,
  CirclePercent as CirclePercentIcon,
  OctagonX as OctagonXIcon,
  TriangleAlert as TriangleAlertIcon,
  Info as InfoIcon,
  Loader2 as Loader2Icon,
  GripVertical as GripVerticalIcon,
  Filter as FilterIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  Star as StarIcon,
  ExternalLink as ExternalLinkIcon,
  ChevronsUpDown as ChevronsUpDownIcon,
  Pencil as PencilIcon,
  Trash2 as Trash2Icon,
  Bookmark as BookmarkIcon,
  Settings as SettingsIcon,
  Link as LinkIcon,
  Image as ImageIcon,
  Menu as MenuIcon,
  Github as GithubIcon,
  Twitter as TwitterIcon,
  SquarePlus as SquarePlusIcon,
  SquarePen as SquarePenIcon,
  Phone as PhoneIcon,
  Save as SaveIcon,
  User as UserIcon,
  Users as UsersIcon,
  LogOut as LogOutIcon,
  HeartHandshake as HeartHandshakeIcon,
  BadgePercent as BadgePercentIcon,
  MonitorSmartphone as MonitorSmartphoneIcon,
  ShoppingCart as ShoppingCartIcon,
  ShoppingBag as ShoppingBagIcon,
  Undo2 as Undo2Icon,
  Folder as FolderIcon,
  FolderSearch as FolderSearchIcon,
  Activity as ActivityIcon,
  Bell as BellIcon,
  ChartPie as ChartPieIcon,
  ChartNoAxesCombined as ChartNoAxesCombinedIcon,
  DollarSign as DollarSignIcon,
  Languages as LanguagesIcon,
  LayoutGrid as LayoutGridIcon,
  Mail as MailIcon,
  Globe as GlobeIcon,
  FileText as FileTextIcon,
  PenTool as PenToolIcon,
  Sparkles as SparklesIcon,
  LifeBuoy as LifeBuoyIcon,
  ShieldCheck as ShieldCheckIcon,
  ChevronsLeft as ChevronsLeftIcon,
  ChevronsRight as ChevronsRightIcon,
  ChevronFirst as ChevronFirstIcon,
  ChevronLast as ChevronLastIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  QrCode as QrCodeIcon,
  Mic2 as Mic2Icon,
  ScanLine as ScanLineIcon,
  AtSign as AtSignIcon,
  FileInput as FileInputIcon,
  ToggleLeft as ToggleLeftIcon,
  Code as CodeIcon,
  Terminal as TerminalIcon,
  Megaphone as MegaphoneIcon,
  Webhook as WebhookIcon,
  MousePointerClick as MousePointerClickIcon,
  Ticket as TicketIcon,
  Radio as RadioIcon,
  Compass as CompassIcon,
  DoorOpen as DoorOpenIcon,
  Presentation as PresentationIcon,
  Utensils as UtensilsIcon,
  Accessibility as AccessibilityIcon,
  CloudSun as CloudSunIcon,
  Timer as TimerIcon,
  BellRing as BellRingIcon,
  Building2 as BuildingIcon,
  Navigation as NavigationIcon,
  Wifi as WifiIcon,
  Bed as BedIcon,
  Car as CarIcon,
  Smartphone as SmartphoneIcon,
  Bus as BusIcon,
  Coffee as CoffeeIcon,
  Map as MapIcon,
  BedDouble as BedDoubleIcon,
}
