#!/usr/bin/env python3
"""Render only declared Workflow Studio documentation projections; no runtime effects."""
import argparse
import json
from pathlib import Path
import subprocess
import sys

PACKAGE = Path(__file__).resolve().parents[1]
REPO = PACKAGE.parents[2]
CHANGE = REPO / "openspec/changes/add-workflow-studio-program-contracts"

def read(name):
    return json.loads((PACKAGE / name).read_text())

def render():
    recipes = read("contracts/recipe-catalog.json")["recipes"]
    plan = read("contracts/delivery-plan.json")
    scenarios = read("verification/acceptance-scenarios.json")["scenarios"]
    requirements = read("contracts/requirements.json")
    generated = "Generated by `tools/render.py` from the canonical machine records. Edit the declared source and regenerate; this is specified work, not execution evidence.\n\n"
    text = "# Recipe catalog\n\n" + generated
    text += "All 96 recipes retain their source identity and full requirements. Delivery ownership does not certify a source adapter. Every optional starter is disabled until source qualification and deliberate tenant activation.\n\n"
    for r in recipes:
        text += f"## {r['id']} — {r['title']}\n\n**Owner:** Phase {r['deliveryPhase']} / {r['checkpoint']}.\n\n"
        for field in ["persona", "customization", "subject", "trigger", "steps", "editable", "protected", "evidence", "sourceDependencyLabels", "dependencyMeaning", "default_activation", "clock_policy", "audience", "idempotency", "exception_policy", "acceptance_ids", "sourceBindingStatus"]:
            value = r[field]
            if isinstance(value, list): value = "; ".join(value)
            text += f"**{field}:** {value}\n\n"
    out = {PACKAGE / "07-core-workflow-catalog.md": text}
    text = "# Effective implementation backlog\n\n" + generated
    text += "All 26 WS identifiers survive in 39 scoped work slices. Only `slices[].dependsOn` is the operative dependency graph. `sourceScope` and `sourceDependsOn` preserve the original package descriptions as historical provenance; they do not reintroduce all-pack gates. CORE requires its real common tracers; FULL is an evidence rollup. Exact source qualification gates still apply to every selected capability.\n\n"
    for pack in plan["packages"]:
        text += f"## {pack['id']} — {pack['title']}\n\n**Whole-package source evidence (allocated across the slices below):** {pack['acceptanceEvidence']}\n\n**Shared test IDs:** {', '.join(pack['crossCuttingTests'])}.\n\n"
        for row in [r for r in plan["slices"] if r["packageId"] == pack["id"]]:
            text += f"### {row['id']}\n\n{row['scope']}\n\n**Depends on:** {', '.join(row['dependsOn']) or 'No preceding Studio slice; exact current source-owner requirements apply'}.\n\n**State:** not started.\n\n"
    out[PACKAGE / "09-implementation-backlog.md"] = text
    text = "# Acceptance scenarios\n\n" + generated
    text += "352 source scenarios: 64 shared invariants and 288 recipe cases. Shared CORE proof uses qualified non-mobilization sources for integration; exact named business-domain cases additionally close under their owner checkpoint. Compiler/simulation fixtures never certify an unavailable source. The eight IG qualification scenarios in the OpenSpec requirement projection are additional seam coverage, not replacements or extra members of the original 352.\n\n"
    for r in scenarios:
        text += f"## {r['id']} — {r['title']}\n\n**Coverage:** {r['checkpoint']}; **state:** {r['status']}.\n\n"
        for field in ["given", "when", "then", "coreProof", "scopeQualification", "authorityQualification"]:
            if field in r: text += f"**{field}:** {r[field]}\n\n"
    out[PACKAGE / "10-acceptance-scenarios.md"] = text
    for capability, records in [("workflow-studio", requirements["workflow"]), ("platform-surfaces", requirements["surfaces"])]:
        text = "<!-- Generated from docs/prds/workflow-studio/contracts/requirements.json by tools/render.py. -->\n\n"
        if capability == "workflow-studio": text += "## Purpose\n\nDefine source-bound tenant workflow authoring, coordination, participant experiences and independently qualified domain delivery without duplicating business authority.\n\n"
        text += "## ADDED Requirements\n\n"
        for r in records:
            text += f"### Requirement: {r['name']}\n\n{r['body']}\n\n"
            for case in r["scenarios"]:
                text += f"#### Scenario: {case['name']}\n\n{case['body']}\n\n"
        out[CHANGE / "specs" / capability / "spec.md"] = text
    text = "# Workflow Studio future implementation tasks\n\n" + generated
    text += "All boxes remain open. Numbered groups identify delivery slices, not completion order; follow the exact DAG in the delivery plan. Each slice must be decomposed into independently verifiable implementation issues before dispatch. A source binding or provider gate remains incomplete until its owner proof exists; no generic test closes a named domain case.\n\n"
    for n, row in enumerate(plan["slices"], 1):
        text += f"## {n}. {row['id']}\n\n**Depends on:** {', '.join(row['dependsOn']) or 'Source foundations only'}.\n\n"
        if row["checkpoint"] == "FULL":
            text += f"- [ ] {n}.1 Reconcile all five completed checkpoint evidence ledgers against 96 recipes, 352 source scenarios and additional IG cases; retain unresolved selected capability gaps.\n- [ ] {n}.2 Record full-program acceptance without making this rollup a prerequisite of CORE or any source checkpoint.\n\n"
        else:
            text += f"- [ ] {n}.1 Bind exact source operations, authority, scope, retained records and qualification gates for {row['id']}; preserve declared predecessors and split issue-sized work.\n"
            text += f"- [ ] {n}.2 Add failing focused tests at the stable seam for the scoped behavior, negative authority/privacy cases and failure/recovery invariants before runtime implementation.\n"
            text += f"- [ ] {n}.3 Implement and qualify: {row['scope']}\n"
            text += f"- [ ] {n}.4 Prove retained-data migration, one effect owner, recovery/rollback, applicable source adapters, database races, browser/accessibility and load/provider evidence; run applicable Core checks and ci:preflight.\n\n"
    out[CHANGE / "tasks.md"] = text
    return out

def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failures = []
    for path, content in render().items():
        formatted = subprocess.run(["bunx", "--no-install", "prettier", "--stdin-filepath", str(path)], input=content, text=True, capture_output=True, cwd=REPO, check=True).stdout
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(formatted)
        elif not path.exists() or path.read_text() != formatted:
            failures.append(str(path.relative_to(REPO)))
    if failures:
        print("Stale generated views: " + ", ".join(failures), file=sys.stderr)
        return 1
    print("Workflow Studio generated views " + ("written" if args.write else "match") + ": 6")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
