import type { ContributionGridRow as Contribution } from "@asym/api/admin/contributions/types";

// Synthetic public component input, derived from the existing contribution contract fixtures.
export function makeMobileContribution(
  overrides: Partial<Contribution> = {},
): Contribution {
  const contribution: Contribution = {
    shared: {
      donationId: "00000000-0000-4000-8000-000000000001",
      amountCents: 10000,
      currencyCode: "USD",
      giftDate: "2026-05-30T00:00:00.000Z",
      donorId: "donor_1",
      donorName: "Fixture Alpha",
      designationSummary: {
        fundId: "fund_1",
        fundName: "General Fund",
        missionaryId: null,
        missionaryName: null,
        lineCount: 1,
      },
      paymentStatus: "completed",
      receiptStatus: "pending",
      crmPostStatus: null,
      refundState: "none",
      refundedAmountCents: 0,
      correctionState: "none",
      recurringLinkState: "none",
    },
    id: "00000000-0000-4000-8000-000000000001",
    donorId: "donor_1",
    donorName: "Fixture Alpha",
    donorEmail: "alpha@example.invalid",
    donorAvatar: null,
    donorType: null,
    donorPhone: null,
    donorLocation: null,
    organizationName: null,
    amount: 10000,
    amountGross: 10000,
    amountNet: null,
    amountFee: null,
    amountTaxDeductible: null,
    currency: "USD",
    date: "2026-05-30T00:00:00.000Z",
    contributionDate: "2026-05-30T00:00:00.000Z",
    createdAt: "2026-05-30T00:00:00.000Z",
    updatedAt: "2026-05-30T00:00:00.000Z",
    settlementDate: null,
    depositDate: null,
    status: "completed",
    subStatus: null,
    type: "One-time",
    paymentMethod: "Credit Card",
    source: "Online",
    fundId: "fund_1",
    fundCode: "GENERAL",
    fundName: "General Fund",
    missionaryId: null,
    missionaryName: null,
    campaignId: null,
    receiptStatus: "pending",
    receiptSent: false,
    receiptSentAt: null,
    stagedGiftId: "00000000-0000-4000-8000-000000000101",
    stagedGiftStatus: "ready_to_post",
    stagedGiftReviewReason: null,
    crmPostStatus: null,
    annualStatementEligible: true,
    entryMethod: "api",
    reconciliationStatus: "unreconciled",
    transactionId: "pi_1",
    externalTransactionId: null,
    processorTransactionId: "pi_1",
    notes: null,
    notesPreview: null,
    isAnonymous: false,
    ...overrides,
  };
  return {
    ...contribution,
    shared: {
      ...contribution.shared,
      donationId: contribution.id,
      donorId: contribution.donorId,
      donorName: contribution.donorName,
    },
  };
}
